<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="PC_1" failures="1" tests="13" name="Personal loans" time="0.065" errors="0" timestamp="2023-06-02T06:31:58 CEST">
  <testcase classname="test.Day_1" name="Demo" time="0.007"/>
  <testcase classname="test.Day_1" name="secondTest" time="0.001"/>
  <testcase classname="test.Day_2" name="anotherTest" time="0.002"/>
  <testcase classname="test.Day_3" name="APILogin_carLoan" time="0.0"/>
  <testcase classname="test.Day_3" name="MobileLogin_2_carLoan" time="0.001"/>
  <testcase classname="test.Day_3" name="MobileLogin_3_carLoan" time="0.001"/>
  <testcase classname="test.Day_3" name="webLogin_carLoan" time="0.001"/>
  <testcase classname="test.Day_4" name="APILogin_homeLoan" time="0.001"/>
  <testcase classname="test.Day_4" name="MobileLogin_homeLoan" time="0.0"/>
  <testcase classname="test.Day_4" name="MobileLogin_homeLoan" time="0.0"/>
  <testcase classname="test.Day_4" name="MobileLogin_homeLoan" time="0.0"/>
  <testcase classname="test.Day_4" name="webLogin_homeLoan" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day_4.webLogin_homeLoan(Day_4.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- webLogin_homeLoan -->
  <testcase classname="test.Day_3" name="MobileLogin_1_carLoan" time="0.003"/>
  <testcase classname="test.Day_2" name="pLoan" time="0.0">
    <ignored/>
  </testcase> <!-- pLoan -->
</testsuite> <!-- Personal loans -->
